<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstractTestCaseGraph" nsURI="http://org.xilaew.atg.model.abstractTestCaseGraph"
    nsPrefix="org.xilaew.atg.model.abstractTestCaseGraph">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGElement" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGContainer" eSuperTypes="#//AbstractTCGElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractTCGNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//AbstractTCGEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGNode" eSuperTypes="#//AbstractTCGElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//AbstractTCGEdge" eOpposite="#//AbstractTCGEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//AbstractTCGEdge" eOpposite="#//AbstractTCGEdge/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGEdge" eSuperTypes="#//AbstractTCGElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractTCGNode" eOpposite="#//AbstractTCGNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractTCGNode" eOpposite="#//AbstractTCGNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//AbstractTCGConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGRealNode" eSuperTypes="#//AbstractTCGNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGPseudoNode" eSuperTypes="#//AbstractTCGNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTCGConstraint" eSuperTypes="#//AbstractTCGElement"/>
</ecore:EPackage>
